
language: ruby
rvm:
- 2.1

python:
- 3.4


addons:
  apt:
    packages:
    - python3-enchant
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
    - ./travis-build
    - python _tests/spellchecker.py

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler

sudo: false



# command to install dependencies
