#!/usr/bin/env bash
set -e # halt script on error

SCVERSION="1.4"

wget https://github.com/stfc/markdown-spellchecker/archive/$SCVERSION.tar.gz -O /tmp/spellchecker.tar.gz
(cd /tmp && tar -xvzf spellchecker.tar.gz)

cp -f .travis-scripts/dictionary.txt /tmp/markdown-spellchecker-$SCVERSION/src/dict.txt

echo
echo spellchecker config:
echo --------------------
cat /tmp/markdown-spellchecker-$SCVERSION/src/config.ini
echo --------------------
echo

pyenv versions
pyenv local 3.6
pip3 install pyenchant

# In a pull request, ${TRAVIS_COMMIT_RANGE} contains the commit range of the PR
# Using it allows to test modified/added files of all PR commits and ensure that
# deleted files are ignored (git diff provides the summary of all the modifications)
if [ -n "${TRAVIS_COMMIT_RANGE}" ]
then
    commit_range=${TRAVIS_COMMIT_RANGE}
    echo "Checking modified MD files in commit range ${commit_range}..."
else
    commit_range="HEAD^"
    echo "Checking modified MD files in last commit..."
fi

# Ignore deleted files
git diff --name-only --diff-filter=d ${commit_range} | grep '\.md$' | xargs -r python3.6 /tmp/markdown-spellchecker-$SCVERSION/src/spellchecker.py || exit 1
