#!/usr/bin/env bash
set -e # halt script on error

SCVERSION="1.4"

wget https://github.com/stfc/markdown-spellchecker/archive/$SCVERSION.tar.gz -O /tmp/spellchecker.tar.gz
(cd /tmp && tar -xvzf spellchecker.tar.gz)

cp -f .travis-scripts/dictionary.txt /tmp/markdown-spellchecker-$SCVERSION/src/dict.txt

echo
echo spellchecker config:
echo --------------------
cat /tmp/markdown-spellchecker-$SCVERSION/src/config.ini
echo --------------------
echo

pyenv versions
pyenv local 3.6
pip3 install pyenchant
git diff --name-only HEAD^ | grep '\.md$' | xargs -r python3.6 /tmp/markdown-spellchecker-$SCVERSION/src/spellchecker.py || exit 1
